name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      HOSTNAME: ${{ secrets.HOSTNAME }} # Public DNS
      USER_NAME: ${{ secrets.USER_NAME }}
      SERVER_PUBLIC_IP: ${{ secrets.SERVER_PUBLIC_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh $USER_NAME@$SERVER_PUBLIC_IP << 'EOF'
            set -e
            echo "Running as: $(whoami)"

            # Clone or update repository
            if [ ! -d "/home/$USER_NAME/fastapi-book-project" ]; then
              git clone https://github.com/theglad-x/fastapi-book-project.git /home/$USER_NAME/fastapi-book-project
            fi
            cd /home/$USER_NAME/fastapi-book-project
            git fetch origin main
            git reset --hard origin/main

            # Install Docker if not installed
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo usermod -aG docker $USER_NAME
            fi

            # Stop and remove existing container
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Build and run the container
            docker build -t fastapi-app .
            docker run -d --name fastapi-app -p 8000:8000 fastapi-app
          EOF

      - name: Verify Deployment
        run: ssh $USER_NAME@$SERVER_PUBLIC_IP "docker ps"
